---
title: "rIG graphs 2"
output: html_document
author: "Amanda van Dyk"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(VGAM)
library(ggplot2)
library(knitr)
```

## R Markdown

This document contains all the code used to draw the graphs in Section 1 and Section 2.1.1 of my research report.




```{r}

seq1 <- seq(0.000001, 10, by=0.001)



# rIG PDF
rig <- function(x,theta, gamma){
  
  inside <- -(x-sqrt(theta*(theta+3*gamma)))^2 #a variable containing the top part of the fraction in the exp
  dens <- sqrt((theta*(theta+3*gamma))/(2*pi*gamma*(x^3)))*exp(inside/(2*gamma*x))
  return(dens)
}
```

This is the graph for Section 1
```{r}

mu <- 2
lambda <- 4
seq1 <- seq(0.000001, 10, by=0.001)

g1 <- rig(seq1, 1, 1)

df1 <- data.frame(
  x = seq1,
  y1=g1,
  z=factor(matrix(1,length(seq1),1)))


graph2 <- ggplot(df1, aes(x, y1))+geom_line()+labs( y="Probability Density") +theme_light() +theme(axis.text=element_text(size=12),  axis.title=element_text(size=12)) +coord_cartesian(xlim=c(0.00,10), ylim=c(0.00,1))  +scale_x_continuous(breaks=seq(0, 10, 2)) + scale_y_continuous(breaks=seq(0, 4, 0.25))+geom_vline(xintercept=2)+geom_vline(aes(xintercept = 1, colour="red"))+ theme(legend.position = "none")

 print(graph2)

```



```{r}

#graphs where we keep gamma=1 and change theta
g1 <- rig(seq1, 0.5, 1)
g2 <- rig(seq1, 1, 1)
g3 <- rig(seq1, 3, 1)



df1 <- data.frame(
  x = seq1,
  y1=g1,
  z=factor(matrix(1,length(seq1),1)))

df2 <- data.frame(
  x = seq1,
  y1=g2,
  z=factor(matrix(2,length(seq1),1))
)

df3 <- data.frame(
  x = seq1,
  y1=g3,
  z=factor(matrix(3,length(seq1),1))
)
 
df4 <-rbind.data.frame(df1, df2, df3)




graph2 <- ggplot(df1, aes(x, y1))+geom_line()+labs( y="Density") +theme_light() +theme(axis.text=element_text(size=12),  axis.title=element_text(size=12)) +coord_cartesian(xlim=c(0.00,10), ylim=c(0.00,1))  +scale_x_continuous(breaks=seq(0, 10, 2)) + scale_y_continuous(breaks=seq(0, 1, 0.25))+geom_vline(xintercept=2)+geom_vline(aes(xintercept = 1, colour="red"))+ theme(legend.position = "none")

 print(graph2)


graph5 <- ggplot(df4, aes(x, y1, linetype=z))+geom_line(size=1.1) +labs(y="Density") +theme_light()+coord_cartesian(xlim=c(0.00,10), ylim=c(0.00,1)) +theme(plot.caption = element_text(hjust=0.5), legend.text.align = 0.5, legend.key.size=unit(1.1, "cm"), legend.key.width=unit(1.1,"cm"), legend.text = element_text(size=12), legend.title = element_text(size=12), axis.text=element_text(size=12),  axis.title=element_text(size=12))+ scale_x_continuous(breaks=seq(0, 10, 2))+ scale_y_continuous(breaks=seq(0, 1, 0.25))+scale_linetype_discrete(name=expression("The value of"~theta~"is:"), labels=c(expression(theta~"= 0.5"), expression(theta~"= 1"), expression(theta~"= 3"))) 


print(graph5)
```

```{r}
#graphs where we keep theta=1 and change gamma
g4 <- rig(seq1, 1, 0.5)
g5 <- rig(seq1, 1, 1)
g6 <- rig(seq1, 1, 3)

df2 <- data.frame(
  x = seq1,
  y1=g4,
  y2=g5,
  y3=g6
)


df5 <- data.frame(
  x = seq1,
  y1=g4,
  z=factor(matrix(1,length(seq1),1)))

df6 <- data.frame(
  x = seq1,
  y1=g5,
  z=factor(matrix(2,length(seq1),1))
)

df7 <- data.frame(
  x = seq1,
  y1=g6,
  z=factor(matrix(3,length(seq1),1))
)
 
df8 <-rbind.data.frame(df5, df6, df7)

graph7 <- ggplot(df8, aes(x, y1, linetype=z))+geom_line(size=1.1) +labs(y="Density") +theme_light()+coord_cartesian(xlim=c(0.00,10), ylim=c(0.00,1)) +theme(plot.caption = element_text(hjust=0.5), legend.text.align = 0.5, legend.key.size=unit(1.1, "cm"), legend.key.width=unit(1.1,"cm"), legend.text = element_text(size=12), legend.title = element_text(size=12), axis.text=element_text(size=12), axis.title=element_text(size=12))+ scale_x_continuous(breaks=seq(0, 10, 2))+ scale_y_continuous(breaks=seq(0, 1, 0.25))+scale_linetype_discrete(name=expression("The value of"~gamma~"is:"), labels=c(expression(gamma~"= 0.5"), expression(gamma~"= 1"), expression(gamma~"= 3"))) 
print(graph7)
```



